"""Génère en.html (version anglaise) à partir de index.html.

Relancer après chaque modification de index.html :
    python build-en.py
Le script s'arrête avec une erreur si un texte attendu n'est plus trouvé
(ce qui veut dire qu'il a changé dans index.html et qu'il faut mettre à jour la traduction ici).
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
SRC = ROOT / "index.html"
OUT = ROOT / "en.html"

# Textes visibles (contenu exact d'un nœud texte entre deux balises)
TEXT = [
    ("Réalisations", "Work"),
    ("À propos", "About"),
    ("Tarifs", "Pricing"),
    ("Audit gratuit", "Free audit"),
    ("Devis gratuit", "Free quote"),
    ("Basé à Casablanca · Clients partout dans le monde", "Based in Casablanca · Clients worldwide"),
    ("Rendez votre activité impossible à manquer.", "Make your business impossible to miss."),
    ("Rendez votre", "Make your"),
    ("activité", "business"),
    ("impossible à manquer.", "impossible to miss."),
    ("Vos clients vous cherchent sur Google.", "Your customers are searching for you on Google."),
    ("S'ils ne vous trouvent pas, ils choisissent votre concurrent.", "If they can't find you, they pick your competitor."),
    ("Je crée votre site professionnel, pensé pour être vu, avec l'hébergement, le domaine et la maintenance inclus.",
     "I build your professional website, designed to be seen, with hosting, domain and maintenance included."),
    ("Voir les packs", "See the plans"),
    ("Voir des exemples", "See examples"),
    ("Sites pro dès", "Pro websites from"),
    ("Maquette offerte en 48h", "Free mockup in 48h"),
    ("Prix en DH, €, $ et FCFA", "Prices in DH, €, $ and FCFA"),
    ("Visites ce mois", "Visits this month"),
    ("Chargement", "Load time"),
    ("0,8 s", "0.8 s"),
    ("Sécurité", "Security"),
    ("HTTPS actif", "HTTPS on"),
    ("restaurant près de moi", "restaurant near me"),
    ("Environ 1 240 000 résultats (0,42 secondes)", "About 1,240,000 results (0.42 seconds)"),
    ("Top 10 des restaurants près de chez vous", "Top 10 restaurants near you"),
    ("Restaurant du centre-ville", "Downtown Restaurant"),
    ("Avis : les restaurants les mieux notés", "Reviews: the best-rated restaurants"),
    ("N°1", "#1"),
    ("Votre restaurant, ouvert 24h/24 en ligne", "Your restaurant, open online 24/7"),
    ("Cabinets d'avocats", "Law firms"),
    ("Cliniques", "Clinics"),
    ("Salons de beauté", "Beauty salons"),
    ("Boutiques", "Shops"),
    ("Immobilier", "Real estate"),
    ("Artisans", "Craftspeople"),
    ("Coachs", "Coaches"),
    ("Écoles", "Schools"),
    ("BTP", "Construction"),
    ("Associations", "Nonprofits"),
    ("des internautes jugent la crédibilité d'une entreprise d'après le design de son site.",
     "of people judge a company's credibility by its website design."),
    ("Source : Stanford Web Credibility Research", "Source: Stanford Web Credibility Research"),
    ("Pourquoi un site web", "Why a website"),
    ("Vos clients vous cherchent.", "Your customers are looking for you."),
    ("Sans site, vous êtes invisible", "Without a website, you're invisible"),
    ("Un client qui ne vous trouve pas en ligne ne vous appelle pas. Il appelle celui qui apparaît en premier.",
     "A customer who can't find you online won't call you. They'll call whoever shows up first."),
    ("Un beau site inspire confiance", "A great website builds trust"),
    ("Une page Facebook ne suffit plus. Un vrai site montre que vous êtes sérieux et établi.",
     "A Facebook page is no longer enough. A real website shows you're serious and established."),
    ("Votre vitrine ouverte 24h/24", "Your storefront, open 24/7"),
    ("Pendant que vous dormez, votre site présente vos services et reçoit des demandes sur WhatsApp.",
     "While you sleep, your website presents your services and receives requests on WhatsApp."),
    ("pour votre première maquette", "for your first mockup"),
    ("responsive mobile", "mobile-friendly"),
    ("votre site travaille pour vous", "your website works for you"),
    ("devises : DH, €, $, FCFA", "currencies: DH, €, $, FCFA"),
    ("Ce que je vous apporte", "What I bring you"),
    ("Un site qui", "A website that"),
    ("travaille pour vous", "works for you"),
    ("Pas une simple vitrine : un outil pensé pour attirer des clients, inspirer confiance et se mettre à jour facilement.",
     "Not just a showcase: a tool built to attract customers, build trust and stay easy to update."),
    ("Design sur mesure", "Custom design"),
    ("Une identité unique et moderne, fidèle à votre marque. Jamais un modèle recyclé.",
     "A unique, modern look that's true to your brand. Never a recycled template."),
    ("Visible sur Google", "Visible on Google"),
    ("Textes et code optimisés SEO, fiche Google Business, mots-clés ciblés sur votre ville.",
     "SEO-optimized copy and code, a Google Business profile, keywords targeted to your city."),
    ("Parfait sur mobile", "Perfect on mobile"),
    ("La majorité de vos visiteurs arrivent sur téléphone. Votre site y sera rapide et impeccable.",
     "Most of your visitors arrive on a phone. Your site will be fast and flawless there."),
    ("Contact WhatsApp", "WhatsApp contact"),
    ("Vos visiteurs vous écrivent en un clic. Les demandes arrivent directement sur votre téléphone.",
     "Visitors message you in one click. Requests land straight on your phone."),
    ("Vous restez autonome", "You stay in control"),
    ("Modifiez vos textes, photos et offres vous-même, sans toucher une ligne de code.",
     "Edit your text, photos and offers yourself, without touching a line of code."),
    ("Suivi des résultats", "Results tracking"),
    ("Un bilan mensuel clair : visiteurs, pages vues, d'où viennent vos clients.",
     "A clear monthly report: visitors, page views, where your customers come from."),
    ("La méthode", "The process"),
    ("De l'idée à la mise en ligne, en 4 étapes", "From idea to launch, in 4 steps"),
    ("Vous validez à chaque étape. Aucune mauvaise surprise.", "You approve every step. No bad surprises."),
    ("On échange", "We talk"),
    ("Sur WhatsApp ou en visio : votre activité, vos objectifs, vos envies. Je vous conseille le bon pack.",
     "On WhatsApp or video call: your business, your goals, your wishes. I recommend the right plan."),
    ("Vous voyez votre futur site avant de payer quoi que ce soit. Vous donnez votre avis, on ajuste ensemble.",
     "You see your future website before paying anything. You give feedback and we adjust together."),
    ("Création", "Build"),
    ("Vous validez la maquette et réglez 50 %. Je crée le site complet : design, textes SEO, images, contact WhatsApp. Comptez 2 à 3 semaines.",
     "You approve the mockup and pay 50%. I build the full site: design, SEO copy, images, WhatsApp contact. Allow 2 to 3 weeks."),
    ("Mise en ligne", "Launch"),
    ("Après votre validation finale, vous réglez le solde et le site est publié. Je reste à vos côtés pour le suivi.",
     "After your final approval, you pay the balance and the site goes live. I stay by your side for follow-up."),
    ("Dois-je payer avant de voir quelque chose ?", "Do I have to pay before seeing anything?"),
    ("Non. Je vous envoie d'abord une maquette offerte sous 48h. Si elle vous plaît, vous réglez 50 % pour lancer la création, puis le solde à la mise en ligne.",
     "No. I first send you a free mockup within 48h. If you like it, you pay 50% to start the build, then the balance at launch."),
    ("Un style pour", "A style for"),
    ("chaque activité", "every business"),
    ("Survolez une carte pour faire défiler le site. Chaque projet reçoit une identité propre.",
     "Hover over a card to scroll through the site. Every project gets its own identity."),
    ("Ambiance photo, carte en ligne, réservation WhatsApp.", "Atmosphere photos, online menu, WhatsApp booking."),
    ("Cabinet d'avocats", "Law firm"),
    ("Image sobre et sérieuse, expertises, équipe, prise de rendez-vous.",
     "A sober, serious image, practice areas, team, appointment booking."),
    ("Boutique en ligne", "Online shop"),
    ("Catalogue, panier, promotions, commande sur WhatsApp.", "Catalog, cart, promotions, ordering via WhatsApp."),
    ("Clinique dentaire", "Dental clinic"),
    ("Style appli, réservation en ligne avec choix du créneau, plan d'accès.",
     "App-like style, online booking with time-slot selection, directions map."),
    ("Concepts de démonstration. Votre site sera conçu sur mesure pour votre activité.",
     "Demo concepts. Your website will be custom-designed for your business."),
    ("Clients partout dans le monde", "Clients worldwide"),
    ("Réponse sous 24h", "Reply within 24h"),
    ("sur WhatsApp", "on WhatsApp"),
    ("Qui suis-je", "About me"),
    ("Un seul interlocuteur,", "One single contact,"),
    ("du premier message à la mise en ligne.", "from first message to launch."),
    ("Je m'appelle Djamila. Ingénieur informatique de formation, j'ai toujours aimé deux mondes : la technique qui fait fonctionner les choses, et l'image qui donne envie. Vuup est né de cette rencontre.",
     "My name is Djamila. A computer engineer by training, I've always loved two worlds: the technology that makes things work, and the image that makes people want more. Vuup was born where they meet."),
    ("Le personal branding, la beauté et le design font partie de mon quotidien. On choisit une entreprise comme on remarque quelqu'un : en un regard. Mon travail, c'est que ce premier regard soit le bon, avec un site beau, rapide, sécurisé et pensé pour Google.",
     "Personal branding, beauty and design are part of my everyday life. People choose a business the way they notice someone: at a glance. My job is to make that first glance count, with a website that's beautiful, fast, secure and built for Google."),
    ("Ingénierie web", "Web engineering"),
    ("Référencement Google", "Google SEO"),
    ("Vous me parlez directement", "You talk to me directly"),
    ("Pas de standard, pas d'intermédiaire.", "No switchboard, no middleman."),
    ("Vos questions ne restent pas sans réponse.", "Your questions never go unanswered."),
    ("Prix écrits d'avance", "Prices in writing upfront"),
    ("Un devis clair avant de commencer.", "A clear quote before we start."),
    ("Tarifs transparents", "Transparent pricing"),
    ("Trois packs clairs,", "Three clear plans,"),
    ("tout compris", "all-inclusive"),
    ("Des frais de conception payés une seule fois, puis un abonnement unique qui couvre l'hébergement, le domaine, la maintenance et la sécurité.",
     "A one-time design fee, then a single subscription covering hosting, domain, maintenance and security."),
    ("Prix de référence en dirhams marocains (MAD).", "Reference prices in Moroccan dirhams (MAD)."),
    ("Essentiel", "Essential"),
    ("Pour lancer une présence pro rapidement : un site court qui va droit au but.",
     "To launch a pro presence fast: a short site that gets straight to the point."),
    ("Conception dès", "Design from"),
    ("HT · payé une seule fois", "excl. tax · paid once"),
    ("puis", "then"),
    ("/mois", "/month"),
    ("dès la mise en ligne · tout inclus", "from launch · all included"),
    ("Site de 1 à 2 pages", "1 to 2-page website"),
    ("Design moderne personnalisé", "Modern custom design"),
    ("Bouton WhatsApp intégré", "Built-in WhatsApp button"),
    ("Fiche Google Business offerte", "Free Google Business profile"),
    ("1 adresse e-mail pro", "1 professional email address"),
    ("Choisir Essentiel", "Choose Essential"),
    ("Le plus choisi", "Most popular"),
    ("Professionnel", "Professional"),
    ("Pour présenter vos services en détail et gagner la confiance de vos clients.",
     "To present your services in detail and win your customers' trust."),
    ("Jusqu'à 5 pages", "Up to 5 pages"),
    ("Rédaction web optimisée SEO", "SEO-optimized web copy"),
    ("3 mots-clés stratégiques", "3 strategic keywords"),
    ("Animations et design premium", "Animations and premium design"),
    ("3 adresses e-mail pro", "3 professional email addresses"),
    ("Choisir Professionnel", "Choose Professional"),
    ("Pour dominer votre marché local avec un site complet et un référencement poussé.",
     "To dominate your local market with a complete website and advanced SEO."),
    ("Jusqu'à 10 pages", "Up to 10 pages"),
    ("SEO avancé · 7 mots-clés et plus", "Advanced SEO · 7+ keywords"),
    ("Site multilingue possible", "Multilingual site available"),
    ("Rapport d'analyse mensuel", "Monthly analytics report"),
    ("5 adresses e-mail pro", "5 professional email addresses"),
    ("Choisir Premium", "Choose Premium"),
    ("Prix hors taxes. Un projet e-commerce ou sur mesure ? Demandez un devis personnalisé.",
     "Prices exclude tax. An e-commerce or custom project? Ask for a tailored quote."),
    ("Simulateur", "Price calculator"),
    ("Calculez le prix de votre site", "Calculate your website's price"),
    ("Choisissez votre pack, ajoutez des options et envoyez l'estimation sur WhatsApp.",
     "Pick your plan, add options and send the estimate on WhatsApp."),
    ("Choisissez votre pack", "Choose your plan"),
    ("1 à 2 pages", "1 to 2 pages"),
    ("jusqu'à 5 pages", "up to 5 pages"),
    ("jusqu'à 10 pages", "up to 10 pages"),
    ("Ajoutez des options (facultatif)", "Add options (optional)"),
    ("Création de logo", "Logo design"),
    ("3 propositions, 2 retouches", "3 proposals, 2 revisions"),
    ("Kit réseaux sociaux", "Social media kit"),
    ("photo de profil, bannières, modèles de posts", "profile picture, banners, post templates"),
    ("Mise en ligne express", "Express launch"),
    ("site livré en 7 jours", "site delivered in 7 days"),
    ("Langue supplémentaire", "Extra language"),
    ("anglais, arabe…", "French, Arabic…"),
    ("Réservation en ligne", "Online booking"),
    ("rendez-vous, tables", "appointments, tables"),
    ("jusqu'à 30 produits", "up to 30 products"),
    ("Pages supplémentaires", "Extra pages"),
    ("par page", "per page"),
    ("Votre récapitulatif", "Your summary"),
    ("① Création du site · une seule fois", "① Website build · one-time"),
    ("À payer pour la création", "To pay for the build"),
    ("② Ensuite, chaque mois", "② Then, every month"),
    ("À partir de la mise en ligne. Hébergement, domaine, maintenance et sécurité inclus.", "Starting from launch. Hosting, domain, maintenance and security included."),
    ("Pack Professionnel", "Professional plan"),
    ("Envoyer sur WhatsApp", "Send on WhatsApp"),
    ("Estimation indicative, hors taxes. Maquette offerte sous 48h, puis devis final confirmé avec vous.",
     "Indicative estimate, excluding tax. Free mockup within 48h, then a final quote confirmed with you."),
    ("Dans l'abonnement mensuel", "In the monthly subscription"),
    ("Tout est inclus. Vous n'avez rien à gérer.", "Everything is included. Nothing for you to manage."),
    ("Hébergement rapide", "Fast hosting"),
    ("Nom de domaine", "Domain name"),
    ("Certificat SSL (HTTPS)", "SSL certificate (HTTPS)"),
    ("Maintenance corrective", "Bug-fix maintenance"),
    ("Sauvegardes automatiques", "Automatic backups"),
    ("Mises à jour de sécurité", "Security updates"),
    ("Support WhatsApp 24–48h", "WhatsApp support within 24–48h"),
    ("Statistiques mensuelles", "Monthly statistics"),
    ("Espace de modification", "Self-editing space"),
    ("Témoignages", "Testimonials"),
    ("Ils nous ont fait confiance", "They trusted us"),
    ("Ce que nos clients disent de leur nouveau site.", "What our clients say about their new website."),
    ("Exemple", "Example"),
    ("« Depuis la mise en ligne, les clients nous trouvent sur Google et réservent directement sur WhatsApp. »",
     "“Since launch, customers find us on Google and book directly on WhatsApp.”"),
    ("« Un site clair et professionnel. Mes clients me disent qu'ils me font davantage confiance. »",
     "“A clear, professional website. My clients tell me they trust me more.”"),
    ("« Je modifie mes produits moi-même en deux minutes. Simple et efficace. »",
     "“I update my products myself in two minutes. Simple and effective.”"),
    ("Restaurateur", "Restaurant owner"),
    ("Consultante", "Consultant"),
    ("Gérante de boutique", "Shop manager"),
    ("Offert", "Free"),
    ("Votre présence en ligne,", "Your online presence,"),
    ("analysée gratuitement.", "analyzed for free."),
    ("Envoyez-moi le nom de votre activité. Je regarde comment vos clients vous trouvent aujourd'hui et je vous envoie un mini-bilan sur WhatsApp, sans engagement.",
     "Send me your business name. I'll look at how customers find you today and send you a short report on WhatsApp, with no commitment."),
    ("Apparaissez-vous sur Google quand on cherche votre métier ?", "Do you show up on Google when people search for what you do?"),
    ("Votre fiche Google Business est-elle complète ?", "Is your Google Business profile complete?"),
    ("Votre site, s'il existe, est-il rapide sur mobile ?", "If you have a website, is it fast on mobile?"),
    ("Que font vos concurrents de mieux que vous ?", "What are your competitors doing better than you?"),
    ("Votre score de visibilité", "Your visibility score"),
    ("Découvrez-le gratuitement", "Find out for free"),
    ("Nom de votre activité", "Business name"),
    ("Ville", "City"),
    ("Site, Instagram ou fiche Google (facultatif)", "Website, Instagram or Google profile (optional)"),
    ("Indiquez le nom de votre activité pour recevoir l'audit.", "Enter your business name to receive the audit."),
    ("Recevoir mon audit gratuit", "Get my free audit"),
    ("Réponse sur WhatsApp sous 48h.", "Reply on WhatsApp within 48h."),
    ("Questions fréquentes", "FAQ"),
    ("Tout ce que vous voulez savoir", "Everything you want to know"),
    ("Que couvre l'abonnement mensuel ?", "What does the monthly subscription cover?"),
    ("L'hébergement, le nom de domaine, le certificat SSL, la maintenance corrective, les sauvegardes, les mises à jour de sécurité, le support et les statistiques. Aucun autre frais récurrent.",
     "Hosting, domain name, SSL certificate, bug-fix maintenance, backups, security updates, support and statistics. No other recurring fees."),
    ("Je ne suis pas au Maroc, c'est possible ?", "I'm not in Morocco. Is that OK?"),
    ("Oui. Je travaille à distance avec des clients au Maroc, en Afrique de l'Ouest et centrale, en Europe et ailleurs. Les échanges se font sur WhatsApp ou en visio, et les prix s'affichent dans votre devise.",
     "Yes. I work remotely with clients in Morocco, West and Central Africa, Europe and beyond. We talk on WhatsApp or video call, and prices are shown in your currency."),
    ("À qui appartient le nom de domaine ?", "Who owns the domain name?"),
    ("Le nom de domaine est enregistré à votre nom. C'est votre adresse sur internet et vous en gardez le contrôle.",
     "The domain name is registered in your name. It's your address on the internet and you stay in control of it."),
    ("Combien de temps pour être en ligne ?", "How long until I'm online?"),
    ("Une première maquette sous 48h, puis 2 à 3 semaines en moyenne pour le site complet. Le délai dépend du nombre de pages et de la rapidité de vos retours.",
     "A first mockup within 48h, then 2 to 3 weeks on average for the full site. Timing depends on the number of pages and how quickly you reply."),
    ("Puis-je modifier mon site moi-même ?", "Can I edit my website myself?"),
    ("Oui, vous changez vos textes, photos et offres depuis un espace simple. Pour ajouter de nouvelles pages, on passe par un devis ou un changement de pack.",
     "Yes, you change your text, photos and offers from a simple dashboard. New pages are added through a quote or a plan upgrade."),
    ("Et pour une boutique en ligne ou un projet sur mesure ?", "What about an online shop or a custom project?"),
    ("C'est possible : e-commerce, réservation, espace membre, fonctionnalités spécifiques. On établit ensemble un devis adapté.",
     "It's possible: e-commerce, booking, member area, specific features. We'll put together a tailored quote."),
    ("Soyez vu, passez devant.", "Get seen, get ahead."),
    ("Décrivez votre projet en quelques mots. Le message part directement sur mon WhatsApp et je vous réponds avec un devis clair sous 24h. Premier échange gratuit et sans engagement.",
     "Describe your project in a few words. The message goes straight to my WhatsApp and I'll reply with a clear quote within 24h. First conversation free, no commitment."),
    ("Retrouvez Vuup sur", "Find Vuup on"),
    ("E-mail", "Email"),
    ("Votre nom", "Your name"),
    ("Votre activité", "Your business"),
    ("Pack souhaité", "Preferred plan"),
    ("Sur mesure / e-commerce", "Custom / e-commerce"),
    ("Je ne sais pas encore", "Not sure yet"),
    ("Pays", "Country"),
    ("Votre projet (facultatif)", "Your project (optional)"),
    ("Indiquez votre nom pour que je sache à qui répondre.", "Enter your name so I know who to reply to."),
    ("WhatsApp s'ouvre avec votre message prêt à envoyer.", "WhatsApp opens with your message ready to send."),
    ("Mentions légales", "Legal notice"),
    ("Confidentialité", "Privacy"),
    ("Conditions de vente", "Terms of sale"),
]

# Attributs (aria-label, placeholder, title, data-*)
ATTR = [
    ('aria-label="Vuup, accueil"', 'aria-label="Vuup, home"'),
    ('aria-label="Navigation principale"', 'aria-label="Main navigation"'),
    ('aria-label="Changer de thème"', 'aria-label="Toggle theme"'),
    ('title="Thème clair / sombre"', 'title="Light / dark theme"'),
    ('aria-label="Animation : votre site passe en première position sur Google"', 'aria-label="Animation: your site climbs to first place on Google"'),
    ('data-tpl="Top 10 des {ws} près de chez vous"', 'data-tpl="Top 10 {ws} near you"'),
    ('data-tpl="{W} du centre-ville"', 'data-tpl="Downtown {W}"'),
    ('data-tpl="Avis : les {ws} les mieux notés"', 'data-tpl="Reviews: the best-rated {ws}"'),
    ('data-tpl="Votre {w}, ouvert 24h/24 en ligne"', 'data-tpl="Your {w}, open online 24/7"'),
    ('aria-label="Secteurs accompagnés"', 'aria-label="Industries we serve"'),
    ('aria-label="Choisir la devise"', 'aria-label="Choose currency"'),
    ('aria-label="Pack"', 'aria-label="Plan"'),
    ('data-label="Création de logo"', 'data-label="Logo design"'),
    ('data-label="Langue supplémentaire"', 'data-label="Extra language"'),
    ('data-label="Réservation en ligne"', 'data-label="Online booking"'),
    ('data-label="Boutique en ligne"', 'data-label="Online shop"'),
    ('data-label="Kit réseaux sociaux"', 'data-label="Social media kit"'),
    ('data-label="Mise en ligne express"', 'data-label="Express launch"'),
    ('aria-label="Retirer une page"', 'aria-label="Remove a page"'),
    ('aria-label="Ajouter une page"', 'aria-label="Add a page"'),
    ('aria-label="5 étoiles"', 'aria-label="5 stars"'),
    ('placeholder="Ex. Restaurant Dar Zitoun"', 'placeholder="E.g. Dar Zitoun Restaurant"'),
    ('placeholder="Ex. Casablanca"', 'placeholder="E.g. Casablanca"'),
    ('placeholder="Ex. instagram.com/monresto"', 'placeholder="E.g. instagram.com/myrestaurant"'),
    ('placeholder="Ex. Amina"', 'placeholder="E.g. Amina"'),
    ('placeholder="Ex. restaurant"', 'placeholder="E.g. restaurant"'),
    ('placeholder="Ex. Maroc"', 'placeholder="E.g. Senegal"'),
    ('placeholder="Ce que vous attendez de votre site"', 'placeholder="What you expect from your website"'),
    ('aria-label="Informations légales"', 'aria-label="Legal information"'),
    ('aria-label="Écrire sur WhatsApp"', 'aria-label="Message on WhatsApp"'),
    ('aria-label="Réseaux sociaux"', 'aria-label="Social media"'),
    ('aria-label="E-mail"', 'aria-label="Email"'),
    ('data-pack="Essentiel"', 'data-pack="Essential"'),
    ('data-pack="Professionnel"', 'data-pack="Professional"'),
    ('value="Essentiel"', 'value="Essential"'),
    ('value="Professionnel"', 'value="Professional"'),
]

# Morceaux de HTML bruts (entités, liens de langue)
RAW = [
    ('Vous trouvent-ils&nbsp;?', 'Do they find you?'),
    ('Prêt à être vu&nbsp;?', 'Ready to be seen?'),
    ('Hôtels &amp; riads', 'Hotels &amp; riads'),
    ('<a class="icon-btn lang" href="en.html" hreflang="en" lang="en" title="English version" aria-label="English version">EN</a>',
     '<a class="icon-btn lang" href="index.html" hreflang="fr" lang="fr" title="Version française" aria-label="Version française">FR</a>'),
    ('<a href="en.html" hreflang="en" lang="en">English</a>', '<a href="index.html" hreflang="fr" lang="fr">Français</a>'),
]

# Chaînes du script
JS = [
    ("var words = ['restaurant','cabinet','boutique','salon','clinique','agence'];",
     "var words = ['restaurant','law firm','boutique','salon','clinic','agency'];"),
    (".replace('{ws}', w + 's')", ".replace('{ws}', /y$/.test(w) ? w.slice(0, -1) + 'ies' : w + 's')"),
    ("var txt = w + ' près de moi';", "var txt = w + ' near me';"),
    ("MAD:'Prix de référence en dirhams marocains (MAD).'", "MAD:'Reference prices in Moroccan dirhams (MAD).'"),
    ("EUR:'Conversion indicative depuis le dirham marocain.'", "EUR:'Indicative conversion from the Moroccan dirham.'"),
    ("USD:'Conversion indicative depuis le dirham marocain.'", "USD:'Indicative conversion from the Moroccan dirham.'"),
    ("XOF:'Conversion indicative depuis le dirham marocain (FCFA, zones UEMOA et CEMAC).'",
     "XOF:'Indicative conversion from the Moroccan dirham (FCFA, WAEMU and CEMAC zones).'"),
    ("toLocaleString('fr-FR')", "toLocaleString('en-US')"),
    ("return n + '<span class=\"sym\">€</span>';", "return '<span class=\"sym\">€</span>' + n;"),
    ("label:'Pack ' + pack.value", "label:pack.value + ' plan'"),
    ("' pages supplémentaires'", "' extra pages'"),
    ("' page supplémentaire'", "' extra page'"),
    ("'Bonjour Vuup ! Voici mon récapitulatif :'", "'Hello Vuup! Here is my summary:'"),
    ("'Création du site (une seule fois) :'", "'Website build (one-time):'"),
    ("'Total création : '", "'Build total: '"),
    ("'Ensuite : '", "'Then: '"),
    ("+ '/mois à partir de la mise en ligne'", "+ '/month starting from launch'"),
    ("it.label + ' : ' + plain", "it.label + ': ' + plain"),
    ("'Pouvez-vous me confirmer le devis ?'", "'Could you confirm the quote?'"),
    ("'Bonjour Vuup ! Je souhaite un audit gratuit de ma présence en ligne.'", "'Hello Vuup! I would like a free audit of my online presence.'"),
    ("'Activité : '", "'Business: '"),
    ("'Ville : '", "'City: '"),
    ("'Lien : '", "'Link: '"),
    ("['Bonjour Vuup !']", "['Hello Vuup!']"),
    ("'Je m\\'appelle '", "'My name is '"),
    ("'Mon activité : '", "'My business: '"),
    ("'Pays : '", "'Country: '"),
    ("'Pack qui m\\'intéresse : '", "'Plan I\\'m interested in: '"),
    ("'Bonjour Vuup ! Je souhaite un devis pour mon site web.'", "'Hello Vuup! I would like a quote for my website.'"),
    ("var SOON = 'bientôt';", "var SOON = 'soon';"),
]


def main():
    src = SRC.read_text(encoding="utf-8")
    cut = src.index("<script>")
    html, js = src[:cut], src[cut:]
    missing = []

    for fr, en in RAW + ATTR:
        if fr not in html:
            missing.append(fr)
        html = html.replace(fr, en)

    for fr, en in TEXT:
        pattern = re.compile(r"(>\s*)" + re.escape(fr) + r"(\s*<)")
        html, n = pattern.subn(lambda m: m.group(1) + en + m.group(2), html)
        if n == 0:
            missing.append(fr)

    for fr, en in JS:
        if fr not in js:
            missing.append(fr)
        js = js.replace(fr, en)

    if missing:
        print("Textes introuvables dans index.html (traduction à mettre à jour) :", file=sys.stderr)
        for m in missing:
            print("  -", m, file=sys.stderr)
        sys.exit(1)

    OUT.write_text(html + js, encoding="utf-8")
    print(f"en.html généré ({len(TEXT)} textes, {len(ATTR)} attributs, {len(JS)} chaînes de script).")


if __name__ == "__main__":
    main()
